name: Lint and Type Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch all submodules recursively
          fetch-depth: 0 # Ensure full history is fetched, useful if submodules require it
          persist-credentials: false # Avoids using GitHub's default credentials for submodules, preventing permission issues

      - name: Install uv package manager
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Pyright
        run: uvx pyright ./viscoin

      - name: Run isort
        run: uvx isort ./viscoin --check-only --diff
